/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "sli_bt_gattdb_def.h"

extern const sli_bt_gattdb_t gattdb;

#define gattdb_service_changed_char           3
#define gattdb_database_hash                  6
#define gattdb_client_support_features        8
#define gattdb_device_name                    11
#define gattdb_manufacturer_name_string       16
#define gattdb_system_id                      18
#define gattdb_temperature_measurement        33
#define gattdb_temperature_type               36
#define gattdb_intermediate_temperature       38
#define gattdb_measurement_interval           41
#define gattdb_valid_range                    43
#define gattdb_ota_control                    46

typedef enum {
  mesh_default                   = 0x0001,
  gattdb_all_caps = 0x0001
} gattdb_cap_t;

#endif // __GATT_DB_H
